
export enum MyProfileActions {
    FETCH_FULL_PROFILE_CURRENT_USER = 'FETCH_FULL_PROFILE_CURRENT_USER',
    FETCH_FULL_PROFILE_CURRENT_USER_SUCCESS = 'FETCH_FULL_PROFILE_CURRENT_USER_SUCCESS',
    FETCH_FULL_PROFILE_CURRENT_USER_FAILED = 'FETCH_FULL_PROFILE_CURRENT_USER_FAILED',
}

export enum AnProfileActions {
    FETCH_FULL_PROFILE_ANOTHER_USER = 'FETCH_FULL_PROFILE_ANOTHER_USER',
    FETCH_FULL_PROFILE_ANOTHER_USER_SUCCESS = 'FETCH_FULL_PROFILE_ANOTHER_USER_SUCCESS',
    FETCH_FULL_PROFILE_ANOTHER_USER_FAILED = 'FETCH_FULL_PROFILE_ANOTHER_USER_FAILED'
}